---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: 在NetApp Console中建立或發現 FSx for ONTAP系統後，您可以管理檔案系統並使用提供備份和復原等功能的NetApp資料服務。 
---
= 在NetApp Console中管理 FSx for ONTAP檔案系統
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在NetApp Console中建立或發現 FSx for ONTAP系統後，您可以透過建立磁碟區、管理儲存虛擬機器、保護資料和管理檔案系統來管理檔案系統。控制台還可讓您使用提供備份和復原、資料分類、資料同步等功能的資料服務。



== 使用NetApp Workloads 管理檔案系統

當您從 NetApp Console Systems 頁面開啟 FSx for ONTAP 系統時，您將進入 NetApp Workloads。Workloads 是一項智慧優化和自動化服務，它採用業界最佳實踐來規劃、配置和運行使用 Amazon FSx for NetApp ONTAP 的關鍵工作負載。

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["了解如何使用NetApp Workloads 管理檔案系統"^]



== 使用ONTAP系統管理員管理檔案系統

您可以使用ONTAP系統管理員介面直接從控制台管理 FSx for ONTAP檔案系統。使用系統管理員需要控制台代理程式或 AWS Lambda 連結。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解如何使用連結"^]



== 使用 Amazon CloudFormation 管理檔案系統

您可以使用 Amazon CloudFormation 設定和管理 FSx for ONTAP檔案系統資源（磁碟區、CIFS 共用、匯出原則等）。

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAP供應商 GitHub 儲存庫"^]



== 將NetApp資料服務與檔案系統結合使用

將NetApp資料服務與您的 FSx for ONTAP檔案系統結合使用，以備份和還原資料、傳輸和同步資料、掃描和分類資料、複製資料以及加快存取或卸載流量。



=== 備份和恢復您的數據

NetApp Backup and Recovery為本地端和雲端的NetApp ONTAP資料、資料庫和虛擬機器提供高效率、安全且經濟的資料保護。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["開始使用NetApp Backup and Recovery"^]



=== 傳輸和同步數據

NetApp Copy and Sync是一種雲端複製和同步服務，用於在本機和雲端物件儲存之間傳輸 NAS 資料。

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["開始使用NetApp Copy and Sync"^]



=== 掃描並分類您的數據

NetApp Data Classification可讓您掃描和分類組織混合多雲中的資料。

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["開始使用NetApp Data Classification"^]



=== 加快存取速度或卸載流量

NetApp Volume Caching在遠端位置提供持久、可寫入的磁碟區。您可以使用磁碟區快取來加快資料存取速度或卸載存取頻繁的磁碟區的流量。

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["開始使用NetApp Volume Caching"^]
