---
sidebar: sidebar 
permalink: use/task-monitor-operations.html 
keywords: monitor jobs, track jobs, monitor, track, NetApp Console, bluexp 
summary: 追蹤 FSx for ONTAP操作並使用NetApp控制台中的 Tracker 監控操作進度。 
---
= 使用NetApp控制台中的 Tracker 監控 FSx for ONTAP操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
監控和追蹤 FSx for ONTAP操作的執行情況，並使用NetApp Console 中的 Tracker 監控作業進度。

.關於此任務
NetApp Console 提供了 Tracker（一項作業監控功能），因此您可以監控和追蹤憑證、FSx for ONTAP和連結操作的進度和狀態，查看操作任務和子任務的詳細信息，並診斷任何問題或故障。

Tracker 中提供了多種操作。您可以按時間範圍（過去 24 小時、7 天、14 天或 30 天）、工作量、狀態和使用者篩選作業；使用搜尋功能尋找作業；並將作業表下載為 CSV 檔案。您可以隨時刷新追蹤器。您可以快速重試失敗的操作或編輯失敗操作的參數並再次嘗試該操作。

Tracker 根據操作支援兩種等級的監控。每個任務（例如檔案系統部署）顯示任務描述、狀態、開始時間、任務持續時間、使用者、區域、代理資源、任務 ID 以及所有相關子任務。您可以查看 API 回應以了解操作期間發生的情況。

帶有範例的追蹤器任務級別::
+
--
* 等級 1（父任務）：追蹤檔案系統部署。
* 第 2 級（子任務）：追蹤與檔案系統部署相關的子任務。


--
運作狀態:: Tracker 中的操作狀態如下：_進行中_、_成功_和_失敗_。
操作頻率:: 操作頻率取決於任務類型和時間表。
事件保留:: 事件在使用者介面中保留 30 天。




== 追蹤和監控操作

使用 Tracker 追蹤和監控NetApp控制台中的操作。

.步驟
. 從NetApp控制台選單中，選擇 *Workloads*，然後選擇 *Administration*。
. 從管理選單中，選擇*追蹤器*。
. 在追蹤器中，查看任務或使用篩選器或搜尋來縮小結果範圍。您也可以透過選擇*匯出 CSV*來下載所有操作的報告。




== 查看 API 請求

在 Codebox 中查看 Tracker 中任務的 API 請求。

.步驟
. 在 Tracker 中，選擇一個任務。
. 選擇三點選單，然後選擇*查看 API 請求*。




== 重試失敗的操作

在 Tracker 中重試失敗的操作。重試失敗的操作將啟動一個新任務，您可以在 Tracker 中監控該任務。

您也可以複製操作失敗的錯誤訊息。


NOTE: 您只能重試一次失敗的操作。

.步驟
. 在 Tracker 中，選擇一個失敗的操作。
. 選擇三點選單，然後選擇*重試*。


.結果
該操作重新啟動並作為新任務出現在 Tracker 中。



== 編輯並重試失敗的操作

編輯失敗操作的參數並在 Tracker 之外重試該操作。

.步驟
. 在 Tracker 中，選擇一個失敗的操作。
. 選擇三點選單，然後選擇*編輯並重試*。
+
您將被重定向到操作頁面，例如磁碟區創建，您可以在其中編輯參數並重試操作。



.結果
操作已重新啟動。前往 Tracker 查看操作狀態。
