---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: 在NetApp控制台中建立或發現 FSx for ONTAP系統後，您可以管理檔案系統並使用提供備份和復原等功能的NetApp資料服務。 
---
= 在NetApp控制台中管理 FSx for ONTAP檔案系統
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在NetApp控制台中建立或發現 FSx for ONTAP系統後，您可以透過建立磁碟區、管理儲存虛擬機器、保護資料和管理檔案系統來管理檔案系統。控制台還可讓您使用提供備份和復原、資料分類、資料同步等功能的資料服務。



== 使用NetApp Workloads 管理檔案系統

當您從NetApp控制台系統頁面開啟 FSx for ONTAP系統時，您將進入NetApp工作負載。  Workloads 是一種智慧優化和自動化服務，它使用行業最佳實踐來設計、設定和操作使用Amazon FSx for NetApp ONTAP 的關鍵工作負載。

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["了解如何使用NetApp Workloads 管理檔案系統"^]



== 使用ONTAP系統管理員管理檔案系統

您可以使用ONTAP系統管理員介面直接從控制台管理 FSx for ONTAP檔案系統。使用系統管理員需要控制台代理程式。



== 使用 Amazon CloudFormation 管理檔案系統

您可以使用 Amazon CloudFormation 設定和管理 FSx for ONTAP檔案系統資源（磁碟區、CIFS 共用、匯出原則等）。

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAP供應商 GitHub 儲存庫"^]



== 將NetApp資料服務與檔案系統結合使用

將NetApp資料服務與您的 FSx for ONTAP檔案系統結合使用，以備份和還原資料、傳輸和同步資料、掃描和分類資料、複製資料以及加快存取或卸載流量。



=== 備份和恢復您的數據

NetApp Backup and Recovery 為本地和雲端的NetApp ONTAP資料、資料庫和虛擬機器提供高效率、安全且經濟的資料保護。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["開始使用NetApp備份與還原"^]



=== 傳輸和同步數據

NetApp Copy and Sync 是一種雲端複製和同步服務，用於在本機和雲端物件儲存之間傳輸 NAS 資料。

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["開始使用NetApp複製和同步"^]



=== 掃描並分類您的數據

NetApp資料分類可讓您掃描和分類組織混合多雲中的資料。

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["開始使用NetApp資料分類"^]



=== 複製數據

複製資料以支援備份和災難復原。可以使用NetApp Replication 完成 FSx for ONTAP檔案系統與Cloud Volumes ONTAP之間，或 FSx for ONTAP檔案系統與本機ONTAP系統之間的資料複製。透過複製，您可以在ONTAP儲存系統之間複製數據，以支援到雲端或雲端之間的備份和災難復原。

link:https://docs.netapp.com/us-en/data-services-replication/task-replicating-data.html["開始使用NetApp Replication"^]

可以透過NetApp控制台系統頁面在兩個 FSx for ONTAP檔案系統之間進行資料複製。

.開始之前
在開始之前請考慮以下事項。

* 要在兩個 FSx for ONTAP檔案系統之間複製數據，您必須選擇一個與檔案系統具有連接的連接器或輸入檔案系統以關聯連結。
* 對於處於可用、已建立或配置錯誤以外的狀態的捲，以及ONTAP版本不相容的捲，不支援複製。


.步驟
. 從NetApp控制台系統頁面中，將來源 FSx for ONTAP檔案系統拖曳到目標 FSx for ONTAP檔案系統的頂部，然後選擇 *複製*。
. 在「建立複製」頁面上，選擇要複製的來源卷，然後按一下「下一步」。
. 在複製目標下，提供以下內容：
+
.. *目標名稱*：目標名稱是在畫布中執行拖放操作時先前選擇的。
.. *儲存虛擬機器名稱*：從下拉式選單中選擇儲存虛擬機器。您選擇的儲存虛擬機器是此複製關係中所有選定磁碟區的目標。
.. *磁碟區名稱*：目標磁碟區名稱自動生成，格式如下 `{OriginalVolumeName}_copy`。您可以使用自動產生的磁碟區名稱或輸入其他磁碟區名稱。
.. *用例*：選擇以下其中一個用例進行複製。根據所選的用例，Workload Factory 會根據最佳實踐在表單中填入建議值。您可以接受建議的數值，也可以在填寫表格時進行變更。
+
*** 遷移：將您的資料傳輸到目標 FSx for ONTAP檔案系統
*** 熱災難復原：確保關鍵工作負載的高可用性和快速災難復原
*** 冷災復原或存檔災難復原：
+
**** 冷災難復原：使用更長的復原時間目標（RTO）和復原點物件（RPO）來降低成本
**** 存檔：複製資料以實現長期儲存和合規性


*** 其他
+
此外，用例選擇決定了複製策略或SnapMirror策略（ONTAP）。用於描述複製策略的術語來自link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["ONTAP 9 文件"^]。

+
**** 對於遷移和其他，複製策略稱為_MirrorAllSnapshots_。  _MirrorAllSnapshots_ 是一種非同步策略，用於鏡像所有快照和最新的活動檔案系統。
**** 對於熱、冷或存檔災難恢復，複製策略稱為_MirrorAndVault_。  _MirrorAndVault_ 是一種非同步和保險庫策略，用於鏡像最新的活動檔案系統以及每日和每週快照。
+
對於所有用例，如果您啟用快照進行長期保留，則預設複製策略為_MirrorAndVault_。





.. *分層策略*：選擇目標磁碟區中儲存的資料的分層策略。分層策略預設為您選擇的用例的建議分層策略。
+
使用 Workload Factory 控制台建立磁碟區時，_平衡（自動）_ 是預設分層策略。有關卷分層策略的更多信息，請參閱link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷儲存容量"^]在 AWS FSx for NetApp ONTAP文件中。請注意，工作負載工廠在工作負載工廠控制台中使用基於用例的名稱來制定分層策略，並在括號中包含 FSx for ONTAP分層策略名稱。

+
如果您選擇了遷移案例，Workload Factory 會自動選擇將來源磁碟區的分層策略複製到目標磁碟區。您可以取消選擇複製分層策略並選擇適用於選擇進行複製的磁碟區的分層策略。

.. *最大傳輸速率*：選擇*限制*並輸入最大傳輸限制（MB/s）。或者，選擇*無限制*。
+
如果沒有限制，網路和應用程式效能可能會下降。或者，我們建議對於關鍵工作負載（例如主要用於災難復原的工作負載）使用 FSx for ONTAP檔案系統的無限傳輸速率。



. 在複製設定下，提供以下內容：
+
.. *複製間隔*：選擇快照從來源磁碟區傳送到目標磁碟區的頻率。
.. *長期保留*：可選地，啟用快照以進行長期保留。長期保留使業務服務即使在整個站點發生故障時也能繼續運行，支援應用程式使用輔助副本透明地進行故障轉移。
+
沒有長期保留的複製使用_MirrorAllSnapshots_策略。啟用長期保留會將 _MirrorAndVault_ 策略指派給複製。

+
如果啟用長期保留，則選擇現有策略或建立新策略來定義要複製的快照和要保留的數量。

+

NOTE: 長期保留需要匹配的來源標籤和目標標籤。如果需要，工作負載工廠可以為您建立缺少的標籤。

+
*** *選擇現有策略*：從下拉式選單中選擇一個現有策略。
*** *建立新策略*：輸入*策略名稱*。


.. *不可變快照*：可選。選擇「啟用不可變快照」以防止在保留期間內刪除此策略中拍攝的快照。
+
*** 以小時、天、月或年設定*保留期*。
*** *快照策略*：在表格中，選擇快照策略頻率和要保留的副本數。您可以選擇多個快照策略。






. 選擇“*創建*”。




=== 加快存取速度或卸載流量

NetApp磁碟區快取在遠端位置提供持久、可寫入的磁碟區。您可以使用磁碟區快取來加快資料存取速度或卸載存取頻繁的磁碟區的流量。

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["開始使用NetApp卷緩存"^]
